- name: modify repository
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - 'deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx'
    - 'deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx'

- name: install
  apt:
    name: "nginx={{ nginx_version }}*"
    state: present
    force: yes
  notify: restart nginx

- name: delete example config
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - '/etc/nginx/conf.d/default.conf'
  notify: restart nginx

- name: modify nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: modify geocountry.conf
  copy:
    src: geocountry.conf
    dest: /etc/nginx/geocountry.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: nginx is enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: modify logrotate conf
  template:
    src: logrotate
    dest: /etc/logrotate.d/nginx
    owner: root
    group: root
    mode: 0644
